[package]
name = "shelfcontrol"
version = "0.1.0"
authors = ["bcorrigan <b.j.corrigan@gmail.com>"]
build = "src/build.rs"

[dependencies]
epub = "1.2"
#epub = { path = "/home/bc/workspace/epub-rs", version = "1.2.0" }
#rusqlite = "0.15.0"
clap = "2"
tantivy = "0.10"
walkdir = "2"
chrono = "0.4"
rouille = "3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
ammonia = "2"
maplit = "1"
itertools = "0.8"
failure = "0.1"
ructe = "^0.7"

[build-dependencies]
ructe = "^0.7"
